openapi: 3.0.0
info:
  title: Pet Shop API Documentation
  description: Pet Shop (Buckhill task) API Documentation
  contact:
    email: irman@outlook.my
  version: 1.0.0
servers: [ ]
security:
  - bearerAuth: [ ]
tags:
  - name: Admin
    description: Admin API endpoint
  - name: User
    description: User API endpoint
  - name: Main
    description: Main page API endpoint
paths:
  /api/v1/admin/login:
    post:
      tags:
        - Admin
      summary: Admin login
      operationId: admin-login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: Email
                password:
                  type: string
                  description: Password
              type: object
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: [ ]
  /api/v1/admin/logout:
    get:
      tags:
        - Admin
      summary: Admin logout
      operationId: admin-logout
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security: [ ]
  /api/v1/admin/create:
    post:
      tags:
        - Admin
      summary: Admin create account
      operationId: admin-create
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
                - avatar
                - address
                - phone_number
              properties:
                first_name:
                  type: string
                  description: User firstname
                last_name:
                  type: string
                  description: User lastname
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
                password_confirmation:
                  type: string
                  description: User password
                avatar:
                  type: string
                  description: Avatar image UUID
                address:
                  type: string
                  description: User main address
                phone_number:
                  type: string
                  description: User main phone number
                marketing:
                  type: string
                  description: User marketing preferences
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: [ ]
  /api/v1/admin/user-listing:
    get:
      tags:
        - Admin
      summary: List all users (non-admin)
      operationId: admin-user-listing
      parameters:
        - name: page
          required: false
          in: query
          schema:
            type: integer
        - name: limit
          required: false
          in: query
          schema:
            type: integer
        - name: sortBy
          required: false
          in: query
          schema:
            type: string
        - name: desc
          required: false
          in: query
          schema:
            type: boolean
        - name: first_name
          required: false
          in: query
          schema:
            type: string
        - name: email
          required: false
          in: query
          schema:
            type: string
        - name: phone
          required: false
          in: query
          schema:
            type: string
        - name: address
          required: false
          in: query
          schema:
            type: string
        - name: created_at
          required: false
          in: query
          schema:
            type: string
        - name: marketing
          required: false
          in: query
          schema:
            type: string
            enum:
              - '0'
              - '1'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  /api/v1/admin/user-edit/{uuid}:
    put:
      tags:
        - Admin
      summary: Edit user
      operationId: admin-user-edit
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
                - address
                - phone_number
              properties:
                first_name:
                  type: string
                  description: User firstname
                last_name:
                  type: string
                  description: User lastname
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
                password_confirmation:
                  type: string
                  description: User password
                avatar:
                  type: string
                  description: Avatar image UUID
                address:
                  type: string
                  description: User main address
                phone_number:
                  type: string
                  description: User main phone number
                is_marketing:
                  type: string
                  description: User marketing preferences
              type: object
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  /api/v1/admin/user-delete/{uuid}:
    delete:
      tags:
        - Admin
      summary: Delete user
      operationId: admin-user-delete
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  /api/v1/user:
    get:
      tags:
        - User
      summary: View a user's own account
      operationId: user-read
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
    delete:
      tags:
        - User
      summary: Delete a user's own account
      operationId: user-delete
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  /api/v1/user/orders:
    get:
      tags:
        - User
      summary: List all orders for current user
      operationId: user-orders-listing
      parameters:
        - name: page
          required: false
          in: query
          schema:
            type: integer
        - name: limit
          required: false
          in: query
          schema:
            type: integer
        - name: sortBy
          required: false
          in: query
          schema:
            type: string
        - name: desc
          required: false
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  /api/v1/user/edit:
    put:
      tags:
        - User
      summary: Update user's own account
      operationId: user-update
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
                - address
                - phone_number
              properties:
                first_name:
                  type: string
                  description: User firstname
                last_name:
                  type: string
                  description: User lastname
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
                password_confirmation:
                  type: string
                  description: User password
                avatar:
                  type: string
                  description: Avatar image UUID
                address:
                  type: string
                  description: User main address
                phone_number:
                  type: string
                  description: User main phone number
                is_marketing:
                  type: string
                  description: User marketing preferences
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  /api/v1/user/login:
    post:
      tags:
        - User
      summary: Login into user account
      operationId: user-login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: [ ]
  /api/v1/user/logout:
    get:
      tags:
        - User
      summary: User logout
      operationId: user-logout
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: [ ]
  /api/v1/user/create:
    post:
      tags:
        - User
      summary: User create
      operationId: user-create
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
                - address
                - phone_number
              properties:
                first_name:
                  type: string
                  description: User firstname
                last_name:
                  type: string
                  description: User lastname
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
                password_confirmation:
                  type: string
                  description: User password
                avatar:
                  type: string
                  description: Avatar image UUID
                address:
                  type: string
                  description: User main address
                phone_number:
                  type: string
                  description: User main phone number
                is_marketing:
                  type: string
                  description: User marketing preferences
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: [ ]
  /api/v1/user/forgot-password:
    post:
      tags:
        - User
      summary: Creates a token to reset a user password
      operationId: user-forgot-pass
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - email
              properties:
                email:
                  type: string
                  description: User email
              type: object
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: [ ]
  /api/v1/user/reset-password-token:
    post:
      tags:
        - User
      summary: Reset a user's password with the a token
      operationId: user-reset-pass-token
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - token
                - email
                - password
                - password_confirmation
              properties:
                token:
                  type: string
                  description: User reset token
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
                password_confirmation:
                  type: string
                  description: User password
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: [ ]
  /api/v1/main/promotions:
    get:
      tags:
        - Main
      summary: List all promotions
      operationId: main-promotions
      parameters:
        - name: page
          required: false
          in: query
          schema:
            type: integer
        - name: limit
          required: false
          in: query
          schema:
            type: integer
        - name: sortBy
          required: false
          in: query
          schema:
            type: string
        - name: desc
          required: false
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  /api/v1/main/blog:
    get:
      tags:
        - Main
      summary: List all blog posts
      operationId: main-blog
      parameters:
        - name: page
          required: false
          in: query
          schema:
            type: integer
        - name: limit
          required: false
          in: query
          schema:
            type: integer
        - name: sortBy
          required: false
          in: query
          schema:
            type: string
        - name: desc
          required: false
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  /api/v1/main/blog/{uuid}:
    get:
      tags:
        - Main
      summary: View blog post
      operationId: main-blog-index
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Blog post not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
